Compilaciones:
	gcc suma.c -o suma.c.cuak
	g++ suma.cpp -o suma.cpp.vrau

Borrar:
	rm suma.c.cuak suma.cpp.vrau

Ejecutar:
	echo "programa Python"
	python suma.py 1 2 3.3
	echo "programa de C"
	./suma 1 2 3.3
	echo "programa de C++"
	./suma.cpp.cuak 1 2 3.3



	
